travis:
  secure:
    BINSTAR_TOKEN: JjIEXSrtbyrmmBkjdtS6o+55YkCvN7rSIPEdNC6exRnSzusLg7Wifvz+Fvwyz+0+SoeiLofB2/nsz9kyhHZNqxIoKU3lTUDtSqd3f2eyKzbLin83Km4axJDOU2b+lINS3rfQHJ6Heved+DVOxOJv/zEl+/Z9uIsEpvLeCPK71ZQ4RTNTfmuoyhUq9eRIMAmGaIyrA1ZHBlAIzMGZAynBpsfzNnG6ganbmjQKK6zRcna65/lWTmKucv7XDJhlNhYx0XEQXr/SdyPhgFsgPS5QC8PDwG5UcGv/7e8YSREEYwzhubNc15jDP+L3DSYOZme7bJxnlBLX8CM0f4iu9Tbv0Rh3owPjI3pkxYbcwFfy/i0j/7Vm0AZ7FqhHJpMUMidZ0UZGDWVSfnalwPRfOabFGhyB/rG2im20/HoyyQcRyxK0HzVToJO8XsSQpZdTBAaPlhnAbae8wYplUb6bHbGyh1He75vXVqbjYkQauntysz6Vvfr2fBn1jZojFYHTw5O58KUQF4kMK46nXq698737lr/+fdNW7lFlKL5j8uaMBcp572K8MxfPibzibka0bN91O4bNDjB8LUY41Uj2kT2SuGWCsTKV1XxOvqzgf/0AxWsVQ7zj9I8X/FJU+WFHlryGM1aGlg2nHqZCGqQ06P0JCEt4eu9zVGcxXqUn8RS1uQM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
